### ISSUE TITLE
The hot reload of CRA/Webpack is breaking the worker when using ES2015 children modules

### ISSUE THREAD

**Issue by nicolas-zozol** [developit/workerize-loader#79] opened 2019-11-21 13:03 UTC
Usng CRA, but also after ejecting the webpack config, I have this code calling the main webworker : 

```js
// App.js - React jsx file
import worker from 'workerize-loader!./worker/main.worker.js';// eslint-disable-line import/no-webpack-loader-syntax

function calculation() {
    const w = worker();
    return w.main(getConfig());
}
```

Then this worker is calling a ES2015 module:

```js
// main.worker.js - entrypoint of the worker module
import {ascii_to_oct} from "./first";

export function main (config){
    return ascii_to_oct("long calculation value");
}
```

And in the child module, I just return a value

```js
first.js
export function ascii_to_oct(str)
{
    return 42
}
```

I run `yarn start` and everything works, but if ever I update  `42` to `43`, I will have the message
`TypeError: w.main is not a function` 

![image](https://user-images.githubusercontent.com/912634/69340348-989fdd80-0c67-11ea-9f6f-67f928aa012d.png)

Then if I restart manually `yarn start`, it works again.

**Comment by nervehammer** [comment] 2020-01-28 09:58
duplicate #24.

**Comment by developit** [comment] 2020-02-21 01:30
Yup, closing as duplicate of #24. Fixed on master, will release shortly.

**Closed as completed by developit** 2020-02-21 01:30 UTC
